### ISSUE TITLE
Performance compared to paper 

### ISSUE THREAD

**Issue by hughwcq** [shinseung428/pix2seq-pytorch#1]
Hi ,
Thank you for making this implementation so fast ! How is the difference of this implementation with the reported numbers in the paper ?

**Comment by shinseung428** [comment]
Hi,
Thank you for your interest. However, the model performance isn't verified yet. 
It's still under training & debugging process. I'll update the README once I get the results.

**Comment by tzayuan** [comment]
Hi, @shinseung428 

if you have any update about performance?

BRs,
zeyuan
